### ISSUE TITLE
sg-project.yaml data doesn't seem to correctly load the data

### ISSUE THREAD

**Issue by matthchr** [Azure/ShieldGuard#109]
```
files:
- name: project-a
  paths:
    - tmp.yaml
  data:
  
  policies:
  - policy/pss-baseline
  - policy/pss-restricted
  - policy/extensions/affinity
  - policy/kubernetes/lib
```

This works

```
files:
- name: project-a
  paths:
    - tmp.yaml
  data:
   - policy/kubernetes/lib
  policies:
  - policy/pss-baseline
  - policy/pss-restricted
  - policy/extensions/affinity
```

This results in the following error:
```
Error: run target (project-a): create queryer failed: failed to create compiler from packages: failed to create compiler: 1 error occurred: /home/matthchr/work/github/aks-extensions-lint/policy/pss-baseline/007-selinux.rego:42: rego_type_error: undefined function data.lib.utils.has_key
```
